### ISSUE TITLE
课程形式的一点修改

### ISSUE THREAD

**Issue by miniflycn** [FE-star/2017.8#2]
> 鉴于大家反馈，我们修改一下，大致上是一半时间讲知识，一半时间做练习。练习尽量提早做吧，上课做应该不完全来得及。

在这里说明一下，我们课程重要的不是上课这三小时，三小时最多只能带你入门。更多的东西要大家看文档，和做练习来思考。我们希望的方式是：“尽可能的模拟真实工作场景，让大家在不断的解决问题过程中提高”。我认为这比讲知识点来的实际，深刻，有意义。

比如我们第一课的设计内容就是一定要所有人学会测试，因为这是之后模拟真实工作场景的基础。这里面我们大纲标明的内容是：

* 学会自己使用 mocha 搭建测试环境
* 学会使用 assert 和 should.js，自己体验这里面的差异
* 学会使用 CI 进行集成测试
* 学会使用 Karma 做真实浏览器测试

可能有同学觉得内容少了，但我真正担心的是如果课上不实操，很多同学可能下课就不会去碰了。而且，有心的话，其实很多东西可以挖掘。

比如：

* 在你的场景，你会对哪些东西做测试？为什么？你要解决什么问题？
* [awesome-node](https://github.com/sindresorhus/awesome-nodejs#testing) 里面那么多测试框架，排在前列的 ava、mocha、tap 有什么差别？
* 对于你的场景而言 ava、mocha、tap 你会选择哪个作为你的测试框架？为什么？
* assert 和 should.js 其实是 TDD 和 BDD 的差别，那 TDD 和 BDD 差别在哪里？对于你的场景而言你会选择哪个库来做测试？
* should.js 是如何做到能够在值后面`.should`的？
* 我们可以用 CI 来做什么别的事情？
* karma 的实现原理是什么？他如何做到把浏览器的测试结果同步给 Node 的？

有发现什么吗？对的，要不就是深入原理，要不就是在自己的场景为了解决什么问题，要怎么选择？

前者需要大家花时间去研究实现细节，这在三小时是讲不完的，因为实在太多东西了。

后者是一个言之有理即可的问题，没有唯一答案，甚至没有正确答案。

请记住，知识点，不是中级前端或高级前端和初级前端的差距，真正的差距是：能根据当前问题，给出多种方案，并能根据问题所处的场景，找出当前最佳的解。这个解只要言之有理即可。

最后，在前端目前的环境来说，会写测试用例，会自己整套CI环境，已经是非常加分的了= =

**Comment by chencye** [comment]
豁然开朗的感觉

感觉自己思维比较局限，视野比较狭窄
老师提的一些示例问题 对我来说帮助非常大

希望 老师以后也能断续提出一些类似课后扩展的问题

**Comment by lalawow** [comment]
老师在上节课里设计的几个例子，挺好的，让我这个以前没碰过测试这一块的新手也能上手，一下子有了感性认识。这正是我上这个课想达到的目的。当然如果想在这一块很精，还是师傅领进门，修行在个人的，需要课后更长时间的学习、练习、领悟。

老师这篇issue写得很好啊。在这个issue里写的“大纲标明的内容”、“延伸思考“的部分，以后每节课也都会有文案来提炼总结出来吧？

**Comment by summer2013** [comment]
1）没有觉得内容少，之前正是因为老师一早就晾出来的课程大纲，都是我感兴趣且欠缺的，所以才加入的
2）做完练习也只是入门了，这周空余时间我还在看测试相关资料呢。要课后加深理解，又要做课前预习时间完全不够啊。老师公开课推荐的《you don't kown JS》这本书真的很喜欢，基础不扎实伤不起啊
3) 对于课上练习做完的同学，老师给点扩展方向，向coverage这种就最好啦：）

**Comment by dorothyLee56** [comment]
谢谢您的举一反三，感觉之前自己不会学习 ，思维太狭隘了。今后还望您多多指教。

**Comment by gilzhao** [comment]
感谢老师的回馈，给到的挖掘点举例，很实在也很受用，真正的经验之谈👍，受教了
